MovieApp/Controllers/GenreController.cs
using MovieAppDAL.Data;
using MovieAppDAL.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace MovieApp.Controllers
{
    public class GenreController : Controller
    {

        private DataGenre _datagenre;

        public GenreController()
        {
            _datagenre = new DataGenre();
        }

        // GET: Genre

        public ActionResult Index()
        {
            List<Genre> generos = _datagenre.GetAll();
            return View(generos);
        }

        // GET: Edit

        public ActionResult Edit(int id)
        {
            Genre genero = _datagenre.GetGenre(id);
            return View(genero);
        }

        // POST: Edit

        [HttpPost]
        public ActionResult Edit(Genre genero)
        {
            _datagenre.Edit(genero);
            return RedirectToAction("Index");
        }

        // GET: Create

        public ActionResult Create()
        {
            return View();
        }

        // POST: Create

        [HttpPost]
        public ActionResult Create(Genre genero)
        {
            _datagenre.Add(genero);
            return RedirectToAction("Index");
        }

        // GET: Details

        public ActionResult Details(int id)
        {
            Genre genero = _datagenre.GetGenre(id);
            return View(genero);
        }

        // GET: Delete

        public ActionResult Delete(int id)
        {
            _datagenre.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

MovieApp/Controllers/GenreEFController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using MovieAppDAL.Data;
using MovieAppDAL.Models;

namespace MovieApp.Controllers
{
    public class GenreEFController : Controller
    {
        private IRepository<Genre> _grepository;

        public GenreEFController(IRepository<Genre> repository)
        {
            _grepository = repository;
        }

        // GET: GenreEF
        public ActionResult Index()
        {
            return View(_grepository.GetAll());
        }

        // GET: GenreEF/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = _grepository.GetOne(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // GET: GenreEF/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GenreEF/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,title,description")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _grepository.Add(genre);
                return RedirectToAction("Index");
            }

            return View(genre);
        }

        // GET: GenreEF/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = _grepository.GetOne(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // POST: GenreEF/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,title,description")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _grepository.Edit(genre);
                return RedirectToAction("Index");
            }
            return View(genre);
        }

        // GET: GenreEF/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = _grepository.GetOne(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // POST: GenreEF/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _grepository.Remove(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }
            base.Dispose(disposing);
        }
    }
}

MovieApp/Controllers/MovieController.cs
using MovieAppDAL.Data;
using MovieAppDAL.Models;
using System.Collections.Generic;
using System.Text;
using System.Web.Mvc;
using Ninject;
using System.Reflection;

namespace MovieApp.Controllers
{
    public class MovieController : Controller
    {
        private DataMovie _datamovie;
        private DataGenre _datagenre;

        public MovieController()
        {
            _datagenre = new DataGenre();
            _datamovie = new DataMovie(_datagenre);
        }

        // GET: Movie
        public ActionResult Index()
        {
            List<Movie> peliculas = _datamovie.GetAll();
            return View(peliculas);
        }
        
        public ActionResult Create()
        {
            ViewBag.miListado = _datagenre.GetAllTitle();
            return View();
        }

        [HttpPost]
        public ActionResult Create(Movie pelicula)
        {
            _datamovie.AddMovie(pelicula);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            _datamovie.DeleteMovie(id);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            ViewBag.miListado = _datagenre.GetAllTitle();
            Movie pelicula = _datamovie.GetMovie(id);
            return View(pelicula);
        }

        [HttpPost]
        public ActionResult Edit(Movie pelicula)
        {
            _datamovie.Edit(pelicula);
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Movie pelicula = _datamovie.GetMovie(id);
            return View(pelicula);
        }

        public void GetFile()
        {
            List<Movie> peliculas = _datamovie.GetAll();

            string filespath = "~/Files";
 
            string path = Server.MapPath(filespath);

            string pathFull = path + "/fichero.txt";

            StringBuilder stringBuilder = new StringBuilder();

            foreach (Movie item in peliculas)
            {
                stringBuilder.AppendLine("ID: "+item.ID);
                stringBuilder.AppendLine("Titulo: "+item.Title);
                stringBuilder.AppendLine("Genero: "+item.Genre);
                stringBuilder.AppendLine("Precio: "+item.Price);
                stringBuilder.AppendLine("Fecha lanzamiento: "+item.ReleaseDate);
                stringBuilder.AppendLine("En cartelera: "+item.EstaEnCartelera);
            }

            System.IO.File.WriteAllText(pathFull , stringBuilder.ToString());

        }

        public JsonResult NumPar(int Price)
        {
            bool esValido = (Price % 2 == 0);
            return Json(esValido, JsonRequestBehavior.AllowGet);
        }
    }
}

MovieApp/Controllers/WebAPIController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;
using MovieAppBL.WebAPI;
using MovieAppDAL.Models;

namespace MovieApp.Controllers
{
    public class WebAPIController : Controller
    {

        // GET: WebAPI

        private IHttpClient client;
        private HttpFactory factory;

        public WebAPIController(HttpFactory pfactory)
        {
            factory = pfactory;
            client = factory.GetHttpClient("http://10.202.10.113:5000/ang/api/Cursos/");
        }

        public ActionResult Index()
        {
            return RedirectToAction("GetCursosAsync");
        }

        public ActionResult GetId()
        {
            return View();
        }

        public ActionResult Post()
        {
            return View();
        }

        public async Task<ActionResult> Delete(int id)
        {
            Curso curso = await client.GetId<Curso>(id); 
            return View(curso);
        }

        public async Task<ActionResult> Put(int id)
        {
            Curso curso = await client.GetId<Curso>(id);
            return View(curso);
        }

        public async Task<ActionResult> GetCursoAsync(int id)
        {
            Curso curso;

            try
            {
                curso = await client.GetId<Curso>(id);
            }

            catch (Exception ex)
            {
                if (ex is HttpRequestException)
                {
                    return Content("El Curso especificado es inválido");
                }            
                return Content("Error no controlado");
            }

            return View("_Details", curso);
        }

        public async Task<ActionResult> GetCursosAsync()
        {
            List<Curso> cursos = new List<Curso>();
            try
            {
                cursos = await client.Get<Curso>();
            }
            catch(Exception ex)
            {
                ViewBag.error = ex.Message;
            }
            
            return View("Listado", cursos);
        }

        [HttpPost]
        public async Task<ActionResult> CreateCursoAsync([Bind(Include = "name,descripcion,horas,max_alumnos,plazas_disponibles,precio")]Curso curso)
        {
            try
            {
                await client.Post<Curso>(curso);
                return RedirectToAction("GetCursosAsync");
            }
            catch(Exception ex)
            {
                ViewBag.error = ex.Message;
                return Json("No se ha podido crear el curso.");
            }
           
        }

        [HttpPost]
        public async Task<ActionResult> EditCursoAsync(Curso curso)
        {
            await client.Put<Curso>(curso, curso.id);
            return RedirectToAction("GetCursosAsync");
        }
        
        [HttpPost]
        public async Task<ActionResult> DeleteConfirm(int id)
        {
            await client.Delete(id);
            return RedirectToAction("GetCursosAsync");
        }

    }

}

MovieApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/jqueryui")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jqueryui")
    <link rel="stylesheet" href="~/Content/custom.css">
    <script src="~/Scripts/sidebar.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
</head>
<body>

    <div class="wrapper">

        <!-- Sidebar -->
        <nav id="sidebar">
            <ul class="list-unstyled components">
                <li class="active">
                    <!-- Link with dropdown items -->
                    <a href="#movieSubmenu" data-toggle="collapse" aria-expanded="false">Peliculas</a>
                    <ul class="collapse list-unstyled" id="movieSubmenu">
                        <li>@Html.ActionLink("Peliculas", "Index", "Movie")</li>
                        <li>@Html.ActionLink("Peliculas EF", "Index", "MovieEF")</li>
                    </ul>
                </li>
                <li>
                    <!-- Link with dropdown items -->
                    <a href="#genreSubmenu" data-toggle="collapse" aria-expanded="false">Generos</a>
                    <ul class="collapse list-unstyled" id="genreSubmenu">
                        <li>@Html.ActionLink("Generos", "Index", "Genre")</li>
                        <li>@Html.ActionLink("Generos EF", "Index", "GenreEF")</li>
                    </ul>
                </li>
                <li>
                <li>
                    <!-- Link with dropdown items -->
                    <a href="#personaSubmenu" data-toggle="collapse" aria-expanded="false">Persona</a>
                    <ul class="collapse list-unstyled" id="personaSubmenu">
                        <li>@Html.ActionLink("Personas", "Index", "Persona")</li>
                        <li>@Html.ActionLink("Autocompletar", "Autocompletar", "Persona")</li>
                        <li>@Html.ActionLink("ListarAjax", "ListarAjax", "Persona")</li>
                        <li>@Html.ActionLink("ListarAjaxAvanzado", "ListarAjaxAvanzado", "Persona")</li>
                    </ul>
                </li>
                <li>
                    <!-- Link with dropdown items -->
                    <a href="#webapiSubmenu" data-toggle="collapse" aria-expanded="false">Web API</a>
                    <ul class="collapse list-unstyled" id="webapiSubmenu">
                        <li>@Html.ActionLink("Get", "GetCursosAsync", "WebAPI")</li>
                        <li>@Html.ActionLink("Post", "Post", "WebAPI")</li>
                    </ul>
                </li>
            </ul>
        </nav>

        <div id="content" class="container body-content">

            <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
                <i class="glyphicon glyphicon-align-left"></i>
                Toggle Sidebar
            </button>

            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
            </footer>
        </div>

</div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>