MovieApp/Models/Persona.cs
using MovieApp.Models.Resources;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Services.Protocols;

namespace MovieApp.Models
{
    public class Persona
    {
        public int id { get; set; }

        [Display(ResourceType = typeof(PersonaResource), Name = "PersonaNameDisplay")]
        [StringLength(30, ErrorMessageResourceType = typeof(PersonaResource), ErrorMessageResourceName = "PersonaNameStringLengthError")]
        public string name { get; set; }

        [Display(ResourceType = typeof(PersonaResource), Name = "PersonaSurnameDisplay")]
        [StringLength(50, ErrorMessageResourceType = typeof(PersonaResource), ErrorMessageResourceName = "PersonaSurnameStringLengthError")]
        public string surname { get; set; }

        [Display(ResourceType = typeof(PersonaResource), Name = "PersonaEmailDisplay")]
        [EmailAddress(ErrorMessageResourceType = typeof(PersonaResource), ErrorMessageResourceName = "PersonaEmailEmailAddressError")]
        public string email { get; set; }

        [NotMapped]
        [Compare("email", ErrorMessageResourceType = typeof(PersonaResource), ErrorMessageResourceName = "PersonaEmailConfirmMatchError")]
        [Display(ResourceType = typeof(PersonaResource), Name="PersonaEmailConfirmDisplay")]
        public string emailconfirm { get; set; }

        [Display(ResourceType = typeof(PersonaResource), Name = "PersonaAgeDisplay")]
        [Range(0,150,ErrorMessageResourceType = typeof(PersonaResource), ErrorMessageResourceName = "PersonaAgeRangeError")]
        public int age { get; set; }

        [CreditCard(ErrorMessageResourceType = typeof(PersonaResource),ErrorMessageResourceName = "PersonaCreditCardError" )]
        [Display(ResourceType = typeof(PersonaResource), Name = "PersonaCreditCardDisplay")]
        public string creditcard { get; set; }
    }
}

MovieApp/Controllers/PersonaController.cs
using MovieAppDAL.Data;
using MovieAppDAL.Models;
using MovieAppDAL.Models.Alimentos;
using Ninject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieApp.Controllers
{
    public class PersonaController : Controller
    {

        private DataPersona _datapersona;

        private IAlimento _alimento;

        public PersonaController([Named("Pizza")]IAlimento alimento)
        {
            _alimento = alimento;
            _datapersona = new DataPersona();
        }

        public ViewResult Index()
        {
            List<Persona> personas = _datapersona.GetAll();
            return View(personas);
        }

        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        public JsonResult CrearPersona(Persona persona)
        {
            BaseResultado _resultado = new BaseResultado();

            if (ModelState.IsValid)
            {
                _datapersona.CrearPersona(persona);
                _resultado.ok = true;
                _resultado.mensaje = "Persona creada";
            }
            else
            {
                _resultado.ok = false;
                _resultado.mensaje = "Error";
            }
            return Json(_resultado);
        }

        public ViewResult ListarAjax()
        {
            return View();
        }

        public PartialViewResult ListarAjaxDo()
        {
            // Buscar personas en BDD 
            var personas = _datapersona.GetAll();
            return PartialView("Index", personas);
        }

        public ViewResult ListarAjaxAvanzado()
        {
            return View();
        }

        public PartialViewResult ListarAjaxAvanzadoDo()
        {
            List<Persona> listado = _datapersona.GetAll();
            return PartialView("_ListadoAjaxDetalles", listado);
        }

        public PartialViewResult DetallePersona(string nombre)
        {
            var persona = _datapersona.GetAll().FirstOrDefault(x => x.Name == nombre);
            return PartialView("_DetallePersona", persona);
        }

        public JsonResult BuscarPersonas(string term)
        {
            var resultado = _datapersona.GetAll().Where(x => x.Name.Contains(term)).Select(x => x.Name).Take(5).ToList();
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        public ViewResult Autocompletar()
        {
            return View();
        }

        public JsonResult Comer()
        {
            var resultado = _alimento.Consumir();
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

    }
}

MovieApp/Views/Persona/Autocompletar.cshtml
@{
    ViewBag.Title = "Autocompletar";
}

<h2>Autocompletar</h2>

Buscar personas: <input type="text" name="persona" id="persona" />

<script>
    $(function(){
        $("#persona").autocomplete({
            source: "@Url.Action("BuscarPersonas","Persona")",
            minLength: 2,
        });
    });
</script> 

MovieApp/Views/Persona/Create.cshtml
@model MovieAppDAL.Models.Persona

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<div class="" id="div-alerta">
    <p id="mensaje-alerta"></p>
    <button type="button" id="btn-cerrar-alerta">Cerrar</button>
</div>

<div class="form-horizontal">
    <h4>Crear persona</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { id = "name", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { id = "surname", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { id = "email", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Emailconfirm, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Emailconfirm, new { htmlAttributes = new { id = "emailconfirm", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Emailconfirm, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { id = "age", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Creditcard, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Creditcard, new { htmlAttributes = new { id = "creditcard", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Creditcard, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button id="btnCrearPersona" class="btn btn-default">Crear Persona</button>
        </div>
    </div>
</div>

<script>

$("#btnCrearPersona").click(function(){

    var txtname = $("#name").val();
    var txtsurname = $("#surname").val();
    var txtage = $("#age").val();
    var txtemail = $("#email").val();
    var txtcreditcard = $("#creditcard").val();
    var txtemailconfirm = $("#emailconfirm").val();

    var url = "@Url.Action("CrearPersona", "Persona")";

    var data = {

        name: txtname,
        surname: txtsurname,
        age: txtage,
        email: txtemail,
        emailconfirm: txtemailconfirm,
        creditcard: txtcreditcard

    };

    $.post(url, data).done(function(data){

        if(data.ok){
            $("#div-alerta").removeClass("alert-danger").addClass("alert-success").slideDown(200);
        }

        else{
            $("#div-alerta").removeClass("alert-success").addClass("alert-danger").slideDown(200);
        }

        $("#mensaje-alerta").html(data.mensaje);

    }).fail();

});

$("#btn-cerrar-alerta").click(function(){
    $(this).parent().slideUp(200);
});

</script>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MovieApp/Views/Persona/Index.cshtml
@model IEnumerable<MovieAppDAL.Models.Persona>

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Creditcard)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Creditcard)
            </td>
        </tr>
    }

</table>

<button type="button" id="comer">Comer</button>
<p id="respuesta"></p>

<script>

    $("#comer").click(function () {

        var url = "@Url.Action("Comer")"
   
        $.get(url).done(function (data) {
            $("#respuesta").html(data);
        }).fail();

    });
        
</script>

MovieApp/Views/Persona/ListarAjax.cshtml
@{
    ViewBag.Title = "ListarAjax";
}

<h2>Listar Ajax</h2>

<button id="btnCargar">Cargar listado</button>

<script>
    $("#btnCargar").click(function(){ 
        $(this).prop("disabled", "disabled"); 
        var url = "@Url.Action("ListarAjaxDo", "Persona")"; 
        $.get(url).done(function (data) { 
            $("#divGet").append(data); 
        }).fail(); 
    }); 
</script>

<div id="divGet"></div>

MovieApp/Views/Persona/ListarAjaxAvanzado.cshtml
@{
    ViewBag.Title = "ListarAjaxAvanzado";
}

<h2>ListarAjaxAvanzado</h2>

@Ajax.ActionLink("Cargar Sección", "ListarAjaxAvanzadoDo",null, new AjaxOptions()
{
    HttpMethod = "GET",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "resultado"
}, new { @class = "btn btn-success" } )

<div id="resultado"></div> 

MovieApp/Views/Persona/_DetallePersona.cshtml
@model MovieAppDAL.Models.Persona

@{
    ViewBag.Title = "_DetallePersona";
}

<h2>_DetallePersona</h2>

<div>
    <h4>Persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Emailconfirm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Emailconfirm)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Creditcard)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Creditcard)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

MovieApp/Views/Persona/_ListadoAjaxDetalles.cshtml
@model List<MovieAppDAL.Models.Persona>
@{
    ViewBag.Title = "ListadoAjaxDetalles";
}

<h2>ListadoAjaxDetalles</h2>

<table class="table">
    <thead>
    </thead>
    <tbody>
        @foreach (var persona in Model){
        <tr>
            <td>
                @Ajax.ActionLink(persona.Name, "DetallePersona", new { nombre = persona.Name }, new AjaxOptions()
                {
                    HttpMethod = "GET",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "DivDetalles"
                })
            </td>
            <td>
                @persona.Surname
            </td>
            <td>
                @persona.Age
            </td>
            <td>
                @persona.Email
            </td>
            <td>
                @persona.Creditcard
            </td>
        </tr>
         }
    </tbody>
</table>

<div id="DivDetalles"></div>